[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["cargo"] }
config = "0.13.3"
csv = "1.3.0"
serde = { version = "1.0.190", features = ["derive"] }
uuid = { version = "1.5.0", features = ["v4"] }
